# Generated by Django 5.0.6 on 2024-06-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_myuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
