# Generated by Django 5.0.6 on 2024-08-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_viewedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='flaged',
            field=models.BooleanField(default=False),
        ),
    ]
