# Generated by Django 5.0.6 on 2024-07-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaminvitation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teamskill',
            unique_together=set(),
        ),
    ]
