# Generated by Django 5.0.6 on 2024-07-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='assigned_to',
        ),
    ]
