# Generated by Django 5.0.6 on 2024-08-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_rename_user_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='other_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
