# Generated by Django 5.0.6 on 2024-08-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_team_github_link_team_other_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
    ]
