# Generated by Django 5.0.6 on 2024-08-07 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_meeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='team_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
