# Generated by Django 5.0.6 on 2024-08-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_meeting_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
