# Generated by Django 5.0.6 on 2024-08-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_remove_meeting_time_meeting_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
