# Generated by Django 5.0.6 on 2024-07-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='community_profile_pic/'),
        ),
    ]
